In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
import pandas as pd
d = pd.read_csv("/content/drive/MyDrive/PROGRAMACION/ETF prices.csv")
d

        fund_symbol  price_date   open   high    low  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
...             ...         ...    ...    ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  27.21  26.30  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.96  26.57  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  28.14  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.56  27.80  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.73  25.91  28.49      28.49  219400

[3866030 rows x 8 columns]

In [8]:
d.shape
#Numero de filas y de columnas

(3866030, 8)

In [9]:
d.ndim
#La dimension de la matriz

2

In [12]:
d.drop(columns = ['high', 'low'])

        fund_symbol  price_date   open  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.01      24.79   12100
...             ...         ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.49      28.49  219400

[3866030 rows x 6 columns]

In [21]:
e =d.drop(columns = ["high","low"])

e

        fund_symbol  price_date   open  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.01      24.79   12100
...             ...         ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.49      28.49  219400

[3866030 rows x 6 columns]

In [25]:
e = d.iloc[0:100]
e
#Selecciona por indices (renglones)

   fund_symbol  price_date   open   high    low  close  adj_close  volume
0          AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1          AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2          AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3          AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4          AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
..         ...         ...    ...    ...    ...    ...        ...     ...
95         AAA  2021-01-26  25.16  25.17  25.16  25.17      25.02     500
96         AAA  2021-01-27  25.14  25.15  25.14  25.15      25.01     500
97         AAA  2021-01-28  25.15  25.15  25.15  25.15      25.01     200
98         AAA  2021-01-29  25.16  25.16  25.15  25.15      25.00    3100
99         AAA  2021-02-01  25.14  25.14  25.13  25.13      25.01    1300

[100 rows x 8 columns]

In [ ]:
#eje 0 es por renglones
# eje 1 es por columnas

In [27]:
e.iloc[:,[1,2,5]]
#Cortar columnas, solo pones las que quieres

    price_date   open  close
0   2020-09-09  25.10  25.07
1   2020-09-10  25.06  25.07
2   2020-09-11  25.04  25.03
3   2020-09-14  25.01  25.02
4   2020-09-15  25.02  25.01
..         ...    ...    ...
95  2021-01-26  25.16  25.17
96  2021-01-27  25.14  25.15
97  2021-01-28  25.15  25.15
98  2021-01-29  25.16  25.15
99  2021-02-01  25.14  25.13

[100 rows x 3 columns]

In [28]:
e.loc[:,'open' : 'close']
#Selecciona las columnas entre x2 y x4

     open   high    low  close
0   25.10  25.12  25.07  25.07
1   25.06  25.07  25.05  25.07
2   25.04  25.05  25.02  25.03
3   25.01  25.06  25.01  25.02
4   25.02  25.03  25.01  25.01
..    ...    ...    ...    ...
95  25.16  25.17  25.16  25.17
96  25.14  25.15  25.14  25.15
97  25.15  25.15  25.15  25.15
98  25.16  25.16  25.15  25.15
99  25.14  25.14  25.13  25.13

[100 rows x 4 columns]

In [29]:
e['open']. value_counts()
#Cuenta los elementos unicos

25.07    8
25.08    8
25.06    7
25.05    6
24.91    5
24.90    5
24.94    5
24.99    5
25.16    5
24.96    4
24.95    4
25.04    4
25.03    3
24.93    3
24.89    3
25.14    3
25.01    3
25.15    3
25.09    2
25.10    2
24.92    2
24.97    2
25.02    2
24.88    2
25.00    1
24.87    1
24.98    1
25.11    1
Name: open, dtype: int64

In [30]:
e.describe()

,open,high,low,close,adj_close,volume
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,25.015900,25.021800,25.011400,25.014900,24.835500,5404.000000
std,0.081353,0.080106,0.081415,0.080735,0.104933,12979.470348
min,24.870000,24.870000,24.870000,24.870000,24.690000,0.000000
25%,24.940000,24.950000,24.940000,24.940000,24.740000,500.000000
50%,25.030000,25.040000,25.025000,25.030000,24.850000,1800.000000
75%,25.070000,25.080000,25.070000,25.070000,24.930000,4500.000000
max,25.160000,25.170000,25.160000,25.170000,25.020000,115400.000000

In [34]:
e

    price_date   open   high    low  close  adj_close  volume
0   2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1   2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2   2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3   2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4   2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
..         ...    ...    ...    ...    ...        ...     ...
95  2021-01-26  25.16  25.17  25.16  25.17      25.02     500
96  2021-01-27  25.14  25.15  25.14  25.15      25.01     500
97  2021-01-28  25.15  25.15  25.15  25.15      25.01     200
98  2021-01-29  25.16  25.16  25.15  25.15      25.00    3100
99  2021-02-01  25.14  25.14  25.13  25.13      25.01    1300

[100 rows x 7 columns]

In [36]:
e.mean(axis =0)
#axis = 0
#axis = 1

<ipython-input-36-95d9e95781c4>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  e.mean(axis =0)

open           25.0159
high           25.0218
low            25.0114
close          25.0149
adj_close      24.8355
volume       5404.0000
dtype: float64